### ISSUE TITLE
As i developer, i would like a cheepslist Partial, so that we can reduce code duplicating when coding pages that display cheeps.

### ISSUE THREAD

**Issue by casperh123** [ITU-BDSA23-GROUP20/Chirp#102]
It would be nice to have a component - in this case a partial, that contains the markup and logic for rendering a list of cheeps.

Acceptance criteria:
*Have a component, that renders cheeps in the same way, that public- and usertimeline currently renders it. 
*The partial should somehow be able to be passed a list of cheeps, and render them correctly.

**Comment by MikkelBKristensen** [comment]
Needs testing before being merged.
