### ISSUE TITLE
As a user, I would like to see a UI element that allows me to go to different pages on the cheep timelines

### ISSUE THREAD

**Issue by Davdu** [ITU-BDSA23-GROUP20/Chirp#124]
Acceptance criteria:
- Pagination UI is present on the site
- Pressing buttons on said UI changes which page is loaded
- Pages display a set number of different cheeps
- There's always a button available for returning to page 1

**Comment by Qezert** [comment]
**Some notes which may prove useful for the future development aimed at resolving this issue:**

*Further requirements:*
If we choose to have next / previous buttons, then only show those when not on first / last page.
If we choose to have individual pages shown around the current page, then make sure that we have enough pages to fill out the expected amount of pages (If we're on page 2, then we can't show 2 pages on either side of this page).


*Pagination logic:*
We should divide amount of cheeps by page number to get amount of filled pages - then check modulo to see if there are more cheeps yet.


*UI implementation:*
Possibly a partial to be implemented on public and user timeline.
Should consist of links (or similar elements) which take the current URL, but change the "page" query value to the value of the chosen page and then redirect to that URL.

**Comment by Qezert** [comment]
Some functionality has been added to the repositories to make pagination possible (commit 4e3cbaf).
Now needs cshtml component / partial with logic behind dynamic buttons / links
