### ISSUE TITLE
Bug) Submitting Follow or Unfollow form also submits CheepBox form

### ISSUE THREAD

**Issue by casperh123** [ITU-BDSA23-GROUP20/Chirp#156]
Acceptance criteria:
*Submitting follow and unfollow does not submit CheepBox.

**Comment by OLaursen** [comment]
This is fixed on the branch "SendCheep_Form-issues", however the branch is not ready for merging yet as sendCheep functionality isn't working yet.

**Comment by Davdu** [comment]
An idea to fix this is by moving the logic to Usertimeline.cshtml.cs instead of public.cshtml.cs
