### ISSUE TITLE
As a User i want to be able to follow/unfollow while on a private usertimeline

### ISSUE THREAD

**Issue by Davdu** [ITU-BDSA23-GROUP20/Chirp#166]
If the user is on an arbitrary users timeline and presses the follow/unfollow button, a null reference appears

Acceptance criteria:
- Pressing the follow/unfollow button on a private usertimeline, the program should not crash
- Pressing the button should perform the appropriate action

**Comment by Qezert** [comment]
Fixed as of 6b8d6ad
