### ISSUE TITLE
Bug) One's own cheeps are shown when you enter another users timeline, while only the cheeps of the other user should be shown

### ISSUE THREAD

**Issue by MikkelBKristensen** [ITU-BDSA23-GROUP20/Chirp#169]
Questions:
* When I enter another users timeline, should both that users cheeps as well as that users followings cheeps be shown? Or only that users cheeps?

Acceptance Criteria:
* Only show the cheeps of the user whom's timeline you have entered.

**Comment by Davdu** [comment]
When entering another authors timeline, only that authors cheeps should be visible. However, on the users own timeline, both the users and every author the user follows' cheeps should be visible
