### ISSUE TITLE
Design choice: The cheepBox is shown while on other users' timelines. Should it?

### ISSUE THREAD

**Issue by MikkelBKristensen** [ITU-BDSA23-GROUP20/Chirp#170]
Acceptance criteria:
* Only show the CheepBox while being on the public or personal timeline

**Comment by OLaursen** [comment]
That is a design choice on our part, in the assignment it was stated that you should be able to "cheep" both from public and user timeline. At the time of the assignment that meant, whether you were on a private or the public timeline. How that translates if we add a private timeline that is different to the user timeline, is up to us.
