### ISSUE TITLE
As a developer I want to isolate UI code in a separate class so that it is easier to maintain

### ISSUE THREAD

**Issue by MikkelBKristensen** [ITU-BDSA23-GROUP20/Chirp#2]
Acceptance criteria:

* All UI concerned code is contained in a single class called UserInterface
* Main program is dependent on the new class for all UI
* The class UserInterface and its methods are static

Definition of Done:

* The above is fulfilled and the program compiles and runs as intended

**Comment by OLaursen** [comment]
The class has been created, however it lacks:
* Connection to the main program
* A concrete way of outputting the cheeps

This will be easy to implement once the CSVparser has a read method.

**Comment by OLaursen** [comment]
As of now the listed acceptance criteria are met. However this issue is closely tied with "Chirp #4 ", which is why me and @MikkelBKristensen are hesitant to consider this issue done.
