### ISSUE TITLE
As a developer i want to know the reason why we choose the given Authentication scheme

### ISSUE THREAD

**Issue by OLaursen** [ITU-BDSA23-GROUP20/Chirp#85]
Description: 
Firstly we as developers need to discuss how we want to implement the login functionality, and as a result choose a way to implement it. 

Acceptance Criteria:
* Document in the project:
   - What we choose
   - Why we chose it
   - What we discussed in terms of pros and cons.

**Comment by OLaursen** [comment]
The documentation could be made in a README.md

**Comment by OLaursen** [comment]
We chose to use ASP.NET CORE Identity, as we could then use the book for more in-depth help with the implementation, however we have yet to document the specific reason for and against it. It should be documented in the README.md in the project.

**Comment by casperh123** [comment]
The website now supports self hosted login and registration. The GitHub OAuth functionality is still a work in progress.
