### ISSUE TITLE
1.a) As developers we want to use *Individual Accounts* and enable GitHub authentication for user registration to establish integrity in our application.

### ISSUE THREAD

**Issue by OLaursen** [ITU-BDSA23-GROUP20/Chirp#88]
Description:
Via 'External 0Auth authentication providers' we can use *Individual Accounts' and enable use of Github to register our users. 
Helge and Rasmus suggests we use chapter 23 when implementing this feature. 

Acceptance criteria:
* Research the subject enough to make subsequent issues leading to the implementation of this feature.

**Comment by casperh123** [comment]
Self login and registration now works. A partial implementation of GitHub Oauth is currently completed, however it does not function properly.

**Comment by casperh123** [comment]
The core implementation works. The problems with the implementation are going to be addressed in issue: #107
